set_property PACKAGE_PIN Y1 [get_ports {x[0]}]
set_property PACKAGE_PIN W3 [get_ports {x[1]}]
set_property PACKAGE_PIN L4 [get_ports and_o]
set_property PACKAGE_PIN M4 [get_ports or_o]
set_property PACKAGE_PIN M2 [get_ports xor_o]
set_property PACKAGE_PIN N7 [get_ports nor_o]
set_property PACKAGE_PIN M7 [get_ports nand_o]

set_property IOSTANDARD LVCMOS33 [get_ports and_o]
set_property IOSTANDARD LVCMOS33 [get_ports nand_o]
set_property IOSTANDARD LVCMOS33 [get_ports nor_o]
set_property IOSTANDARD LVCMOS33 [get_ports or_o]
set_property IOSTANDARD LVCMOS33 [get_ports xor_o]
set_property IOSTANDARD LVCMOS33 [get_ports {x[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {x[0]}]
